name: Deploy Blog

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          install -m 700 -d ~/.ssh 
          printf '%s\n' "$SSH_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa 
          cat >> ~/.ssh/config <<'EOF' 
            Host raspberrypi 
            HostName 100.85.247.33 
            User deploy-jmp 
            IdentityFile ~/.ssh/id_rsa 
            IdentitiesOnly yes 
            StrictHostKeyChecking no 
            
            Host lxc103 
            HostName 192.168.178.103 
            User deploy 
            ProxyJump raspberrypi 
            IdentityFile ~/.ssh/id_rsa 
            IdentitiesOnly yes 
            StrictHostKeyChecking no 
          EOF

      - name: Deploy website
        run: |
          rsync -rltvz --no-times . lxc103:/www/
